# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: rny99
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-nodejs-api

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1

package: 
  individually: true


functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
    # The above line creates an HTTP API Gateway endpoint that triggers the function.
    # The "*" means it will respond to all HTTP methods (GET, POST, PUT, DELETE, etc.)
    # You can specify a specific method like this:
    # - httpApi:
    #     method: get
        cors: true
    # The above line enables CORS for the API Gateway endpoint.
    # You can customize the CORS settings further if needed.
    # For example, you can specify allowed origins, headers, etc.


plugins:
  - serverless-offline